sudo: false  # to use new infrastructure
language: java
#jdk:
#  - openjdk7
#  - oraclejdk8
install: "mvn clean install --batch-mode"
script: "mvn -Djava.awt.headless=true cobertura:cobertura -Dcobertura.report.format=xml test --fail-at-end --batch-mode"
after_success:
  - bash <(curl -s https://codecov.io/bash)